services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: im-principes-server
    env_file:
      - ${ENV_FILE}
    depends_on:
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always

  database:
    image: mysql:9.0.0
    container_name: im-principes-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - im-principes-database:/var/lib/mysql

volumes:
  im-principes-database: