server:
  port: ${SPRING_PORT}
  servlet:
    context-path: ${BASE_PATH}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect

  web3j:
    rpc-url: http://localhost:8545 # private network url
